stages:
  - notice
  # - check
  - build
  - deploy
#  - publish

variables:
  PATH: /opt/go/go/bin/:/opt/node/node/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
  GOROOT: /opt/go/go
  GOPROXY: https://goproxy.cn
  SAVE_DIR: /opt/apinto
  VERSION: $CI_COMMIT_SHORT_SHA
  APP: apinto
  APP_PRE: ${APP}-${VERSION}
  BUILD_DIR: apserver-build

default:
  before_script:
    - pwd

merge-informer: # 飞书回调
  stage: notice
  variables:
    DIFF_URL: "$CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID/diffs"
  rules:
    - if: $CI_PIPELINE_SOURCE=="merge_request_event"
  script:
    - rm -rf out/apinto-*
    - |
      curl -X POST -H "Content-Type: application/json" \
      -d "{\"msg_type\":\"text\",\"content\":{\"text\":\"项目：${CI_PROJECT_NAME}\\n提交人：${GITLAB_USER_NAME}\\n提交信息：${CI_MERGE_REQUEST_TITLE}\\n合并分支信息：${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} -> ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}\\n差异性地址：${DIFF_URL}\\n请及时review代码\"}}" \
      https://open.feishu.cn/open-apis/bot/v2/hook/1c334752-2874-41a1-8f1b-3060f2d46b6c

builder:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH=="main"
  script:
#    - sed -i '/replace github.com\/eolinker\/eosc => */d' go.mod
    - cd ../eosc && git pull && cd ../apinto
    - go mod tidy
    - cd build/cmd && ./package.sh $VERSION
  cache:
    paths:
      - out/
deployer:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH=="main"
      variables:
        DEPLOY_DESC: "DEV 环境"
        APINTO_DEBUG: "true"
  dependencies:
    - builder
  script:
    - cp out/${APP_PRE}.linux.x64.tar.gz ${SAVE_DIR}
    - cd ${SAVE_DIR};cd ${SAVE_DIR}; mkdir -p ${APP_PRE};tar -zxvf ${APP_PRE}.linux.x64.tar.gz -C ${APP_PRE};cd ${APP_PRE}/${APP}
    - ln -snF ${SAVE_DIR}/etc/* ./ 
    - ./apinto stop
    - sleep 10s
    - ./apinto start
    - ps -ef | grep apinto
    - cd ${SAVE_DIR}; ./clean.sh ${APP_PRE}
    - |
      curl -X POST -H "Content-Type: application/json" \
      -d "{\"msg_type\":\"text\",\"content\":{\"text\":\"项目：apinto\\n环境：${DEPLOY_DESC}\\n更新部署完成.\"}}" \
      https://open.feishu.cn/open-apis/bot/v2/hook/1c334752-2874-41a1-8f1b-3060f2d46b6c
  when: on_success
  cache:
    paths:
      - out/