service:
  -
    name: guest  #必填，服务实例名
    driver: http  #必填，服务所使用驱动
    desc: "游客服务"  #非必填，对该服务的描述
    scheme: http  #非必填，服务所使用的scheme，不填则为http。若使用了负载实例，则跟随负载的scheme
    timeout: 30000  #必填，超时时间
    upstream: product-user@upstream  #必填，若使用负载，可填该服务所使用的负载实例的id或名称， 若不使用负载，则直接填服务请求的地址
    retry: 2  #必填，重试次数
    rewrite_url: /Web/Test/params/print  #必填，重写转发至负载的url字段
    proxy_method: GET #非必填，负载转发请求所使用的Method,不填则跟随原请求的Method
    auth: #非必填，该服务使用的鉴权实例，通过其一即可，不填则不使用鉴权
      - basic_1@auth
      - ak/sk_1@auth
      - apikey_1@auth
  -
    name: member
    driver: http
    desc: "会员服务"
    scheme: http  #非必填，服务所使用的scheme，不填则为http。若使用了负载实例，则跟随负载的scheme
    timeout: 30000
    retry: 2
    upstream: www.eolinker.com  #必填，若使用负载，可填该服务所使用的负载实例的id或名称， 若不使用负载，则直接填服务请求的地址
    rewrite_url: /abc
    proxy_method: GET #非必填，负载转发请求所使用的Method,不填则跟随原请求的Method