version: 2 # 配置版本，新版本为2，非 2 当做旧版本
client:
  listen_urls:
    - http://0.0.0.0:9400 # open api 服务的监听地址
gateway: # 网关服务配置
  listen_urls: # 监听地址
    - http://0.0.0.0:8099
peer: # 节点通信配置
  listen_urls: # 监听地址
    - http://0.0.0.0:9401