listen:
  - 80
  - 8080
ssl:
  listen:
    - port: 8443
      certificate:    # 不配表示使用所有 cert_dir中的证书，默认pem文件后缀为pem，key后缀为key
      - cert: cert.pem
        key:  cert.key
      - cert: cert.pem
        key: cert.key
    - port: 443
      certificate:    # 不配表示使用所有 cert_dir中的证书，默认pem文件后缀为pem，key后缀为key
      - cert: cert.pem
        key:  cert.key
  certificate: ./cert # 证书文件目录，不填则默认从cert目录下载

admin:
  scheme: http-service
  listen: 9400
  ip: 0.0.0.0